### PR TITLE
Add support for fabric with HPU

### PR DESCRIPTION
**Pull request by jerome-habana**
<details>
  <summary><b>Before submitting</b></summary>

- [ ] Was this discussed/agreed via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/pytorch-lightning/blob/main/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

</details>

## What does this PR do?

Fixes # (issue).

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in GitHub issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Review by Borda — COMMENTED** [review]
is there really so much difference in the implementations, would it be better just to implement some internal switch in case you use it with fabric or PL?

**Comment by jerome-habana** [comment]
> is there really so much difference in the implementations, would it be better just to implement some internal switch in case you use it with fabric or PL?

majorly imports and initial focus for the upcoming features will be more towards pytorch followed by fabric. So better to keep it separate

**Comment by Borda** [comment]
> majorly imports and initial focus for the upcoming features will be more towards pytorch followed by fabric. So better to keep it separate

sounds good so how about hove about switching the 1st and second levels of the package so the
```
habana
 |- accelartors
 |  |- fabric_hpu.py
 |  ...
 |- strategies
 |  |- fabric_single_device.py
 |  |- fabric_multidievice_device.py
 |  |- pl_single_device.py
    ...
```

**Comment by Borda** [comment]
> I have a subsequent change which will restructure the files similar to the core repo. Lets maintain in the same hierarchy so that its easy to bring in changes.

The suggestion is such that in the accelerator's folder, there are multiple, not as this PR has in accelerators just one...

**Pull request merged**
