### PR TITLE
preparation for parallel agents

### PR DESCRIPTION
**Pull request by assassin1991**
<details>
  <summary><b>preparation for parallel agents</b></summary>

- [ ] Was this discussed/agreed via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/pytorch-lightning/blob/main/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

</details>

## What does this PR do?

Fixes # (issue).

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in GitHub issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
still seeing:
```
>           object_sizes_tensor = object_sizes_tensor.to(current_device)
E           RuntimeError: synStatus=8 [Device not found] Device acquire failed.

**Comment by jerome-habana** [comment]
> still seeing:
> 
> ```
> >           object_sizes_tensor = object_sizes_tensor.to(current_device)
> E           RuntimeError: synStatus=8 [Device not found] Device acquire failed.
> ```

visible_modules for each agent needs to be updated. I see 0,1 used for all.

**Comment by Borda** [comment]
> > still seeing:
> > ```
> > >           object_sizes_tensor = object_sizes_tensor.to(current_device)
> > E           RuntimeError: synStatus=8 [Device not found] Device acquire failed.
> > ```
> 
> visible_modules for each agent needs to be updated. I see 0,1 used for all.

Yes but in this config all agents are running the 0,1

Later it will be updated in #112

**Comment by jerome-habana** [comment]
> > > still seeing:
> > > ```
> > > >           object_sizes_tensor = object_sizes_tensor.to(current_device)
> > > E           RuntimeError: synStatus=8 [Device not found] Device acquire failed.
> > > ```
> > 
> > 
> > visible_modules for each agent needs to be updated. I see 0,1 used for all.
> 
> Yes but in this config all agents are running the 0,1
> 
> Later it will be updated in #112

They are happening parallely which will result in failure.

**Comment by Borda** [comment]
> They are happening parallely which will result in failure.

ok, added `MODULE_ID` to #112

**Comment by Borda** [comment]
@jerome-habana after merging #112 what else from this PR shall be added?

**Comment by jerome-habana** [comment]
> @jerome-habana after merging #112 what else from this PR shall be added?

the test updates will be needed so that its scalable with tenancy

**Pull request merged**
